export const FEEDS_ON_INIT: 'FEEDS_ON_INIT' = 'FEEDS_ON_INIT'
export const FEEDS_ON_OPEN: 'FEEDS_ON_OPEN' = 'FEEDS_ON_OPEN'
export const FEEDS_ON_CLOSE: 'FEEDS_ON_CLOSE' = 'FEEDS_ON_CLOSE'
export const FEEDS_ON_MESSAGE: 'FEEDS_ON_MESSAGE' = 'FEEDS_ON_MESSAGE'
export const FEEDS_ON_ERROR: 'FEEDS_ON_ERROR' = 'FEEDS_ON_ERROR'

